# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
