# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bios',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.TextField(blank=True),
        ),
    ]
