# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170611_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='missions_completed',
            field=models.ManyToManyField(blank=True, related_name='missions_completed', to='missionboard.Mission'),
        ),
        migrations.AlterField(
            model_name='member',
            name='missions_failed',
            field=models.ManyToManyField(blank=True, related_name='missions_failed', to='missionboard.Mission'),
        ),
        migrations.AlterField(
            model_name='member',
            name='missions_wip',
            field=models.ManyToManyField(blank=True, related_name='missions_wip', to='missionboard.Mission'),
        ),
        migrations.AlterField(
            model_name='member',
            name='partners',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
